### ISSUE TITLE
Selecting different authors

### ISSUE THREAD

**Issue by caffarattig** [harpomaxx/harpoquotes#1]
Due to the considerably high demand of quotes but the relatively low amounts of Harpos to pronounce those quotes in the day-time as we know it from Einstein Relativity's Theory, it's necessary the creation of an author selection, with its respective picture, so different authors can have different quotes. In that way, Harpo will feel its burden alleviated.

**Comment by harpomaxx** [comment]
implemented by commit b76fb8597fafb68799e6b8bf385e5622bed5a693
